<a href="https://colab.research.google.com/github/DinaShaim/GB_ML_MathStat/blob/main/%D0%94%D0%BE%D0%BC%D0%B0%D1%88%D0%BD%D1%8F%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_%D0%9C%D0%B0%D1%82%D1%81%D1%82%D0%B0%D1%82_%D0%A3%D1%80%D0%BE%D0%BA_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Домашняя работа 8
### Дисперсионный анализ. Логистическая регрессия

**Задание 1** 

Провести дисперсионный анализ для определения того, есть ли различия среднего роста среди взрослых футболистов, хоккеистов и штангистов.
Даны значения роста в трех группах случайно выбранных спортсменов:
Футболисты: 173, 175, 180, 178, 177, 185, 183, 182.
Хоккеисты: 177, 179, 180, 188, 177, 172, 171, 184, 180.
Штангисты: 172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170.

**Решение**



In [2]:
import numpy as np
from scipy import stats 

Всего три группы: футболисты, хоккеисты и штангисты. Значения роста в этих группах обозначим соответственно $y1$, $y2$, $y3$:


In [3]:
y1 = np.array([173, 175, 180, 178, 177, 185, 183, 182])
y1

array([173, 175, 180, 178, 177, 185, 183, 182])

In [4]:
y2 = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180])
y2

array([177, 179, 180, 188, 177, 172, 171, 184, 180])

In [5]:
y3 = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])
y3

array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])

Применим функция, stats.f_oneway для проведения дисперсионного анализа

In [6]:
stats.f_oneway(y1, y2, y3)

F_onewayResult(statistic=5.500053450812596, pvalue=0.010482206918698694)

Поскольку полученное значение pvalue меньше 0,05, то можно сделать вывод, что вид спорта влияет на средний рост спортсмена. 